
name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          cd app/backend
          pip install -r requirements.txt 

      - name: Lint python
        run: pylint --disable=C app/
