
name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [01_hello_world_api, 02_templating, 03_in_memory_storage, 04_add_images, 05_add_blob_storage]
        include:
            - folder: 04_add_images
              tests: true
    container:
      image: mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          cd modules/${{ matrix.folder }}
          pip install -r requirements.txt

      - name: Lint python
        run: |
          cd modules/
          pylint --disable=C,R0801 ./${{ matrix.folder }}
      
      - if: ${{ matrix.tests }}
        name: Run tests
        run: | 
          cd modules/${{ matrix.folder }}
          pytest 
